/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HorsesIndexRouteImport } from './routes/horses/index'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments/index'
import { Route as HorsesCreateRouteImport } from './routes/horses/create'
import { Route as AppointmentsUpdateRouteImport } from './routes/appointments/update'
import { Route as AppointmentsCreateRouteImport } from './routes/appointments/create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HorsesIndexRoute = HorsesIndexRouteImport.update({
  id: '/horses/',
  path: '/horses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const HorsesCreateRoute = HorsesCreateRouteImport.update({
  id: '/horses/create',
  path: '/horses/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsUpdateRoute = AppointmentsUpdateRouteImport.update({
  id: '/appointments/update',
  path: '/appointments/update',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsCreateRoute = AppointmentsCreateRouteImport.update({
  id: '/appointments/create',
  path: '/appointments/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/appointments/create': typeof AppointmentsCreateRoute
  '/appointments/update': typeof AppointmentsUpdateRoute
  '/horses/create': typeof HorsesCreateRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/horses/': typeof HorsesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/appointments/create': typeof AppointmentsCreateRoute
  '/appointments/update': typeof AppointmentsUpdateRoute
  '/horses/create': typeof HorsesCreateRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/horses': typeof HorsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/appointments/create': typeof AppointmentsCreateRoute
  '/appointments/update': typeof AppointmentsUpdateRoute
  '/horses/create': typeof HorsesCreateRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/horses/': typeof HorsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/appointments/create'
    | '/appointments/update'
    | '/horses/create'
    | '/appointments/'
    | '/horses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/appointments/create'
    | '/appointments/update'
    | '/horses/create'
    | '/appointments'
    | '/horses'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/appointments/create'
    | '/appointments/update'
    | '/horses/create'
    | '/appointments/'
    | '/horses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  AppointmentsCreateRoute: typeof AppointmentsCreateRoute
  AppointmentsUpdateRoute: typeof AppointmentsUpdateRoute
  HorsesCreateRoute: typeof HorsesCreateRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  HorsesIndexRoute: typeof HorsesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horses/': {
      id: '/horses/'
      path: '/horses'
      fullPath: '/horses/'
      preLoaderRoute: typeof HorsesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horses/create': {
      id: '/horses/create'
      path: '/horses/create'
      fullPath: '/horses/create'
      preLoaderRoute: typeof HorsesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/update': {
      id: '/appointments/update'
      path: '/appointments/update'
      fullPath: '/appointments/update'
      preLoaderRoute: typeof AppointmentsUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/create': {
      id: '/appointments/create'
      path: '/appointments/create'
      fullPath: '/appointments/create'
      preLoaderRoute: typeof AppointmentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  AppointmentsCreateRoute: AppointmentsCreateRoute,
  AppointmentsUpdateRoute: AppointmentsUpdateRoute,
  HorsesCreateRoute: HorsesCreateRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  HorsesIndexRoute: HorsesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
