/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedHorsesIndexRouteImport } from './routes/_authenticated/horses/index'
import { Route as AuthenticatedEmployeesIndexRouteImport } from './routes/_authenticated/employees/index'
import { Route as AuthenticatedAppointmentsIndexRouteImport } from './routes/_authenticated/appointments/index'
import { Route as AuthenticatedHorsesCreateRouteImport } from './routes/_authenticated/horses/create'
import { Route as AuthenticatedAppointmentsUpdateRouteImport } from './routes/_authenticated/appointments/update'
import { Route as AuthenticatedAppointmentsCreateRouteImport } from './routes/_authenticated/appointments/create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHorsesIndexRoute =
  AuthenticatedHorsesIndexRouteImport.update({
    id: '/horses/',
    path: '/horses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeesIndexRoute =
  AuthenticatedEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppointmentsIndexRoute =
  AuthenticatedAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHorsesCreateRoute =
  AuthenticatedHorsesCreateRouteImport.update({
    id: '/horses/create',
    path: '/horses/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppointmentsUpdateRoute =
  AuthenticatedAppointmentsUpdateRouteImport.update({
    id: '/appointments/update',
    path: '/appointments/update',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppointmentsCreateRoute =
  AuthenticatedAppointmentsCreateRouteImport.update({
    id: '/appointments/create',
    path: '/appointments/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/about': typeof AuthenticatedAboutRoute
  '/appointments/create': typeof AuthenticatedAppointmentsCreateRoute
  '/appointments/update': typeof AuthenticatedAppointmentsUpdateRoute
  '/horses/create': typeof AuthenticatedHorsesCreateRoute
  '/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/horses/': typeof AuthenticatedHorsesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof AuthenticatedAboutRoute
  '/': typeof AuthenticatedIndexRoute
  '/appointments/create': typeof AuthenticatedAppointmentsCreateRoute
  '/appointments/update': typeof AuthenticatedAppointmentsUpdateRoute
  '/horses/create': typeof AuthenticatedHorsesCreateRoute
  '/appointments': typeof AuthenticatedAppointmentsIndexRoute
  '/employees': typeof AuthenticatedEmployeesIndexRoute
  '/horses': typeof AuthenticatedHorsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/appointments/create': typeof AuthenticatedAppointmentsCreateRoute
  '/_authenticated/appointments/update': typeof AuthenticatedAppointmentsUpdateRoute
  '/_authenticated/horses/create': typeof AuthenticatedHorsesCreateRoute
  '/_authenticated/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/_authenticated/employees/': typeof AuthenticatedEmployeesIndexRoute
  '/_authenticated/horses/': typeof AuthenticatedHorsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/appointments/create'
    | '/appointments/update'
    | '/horses/create'
    | '/appointments/'
    | '/employees/'
    | '/horses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/'
    | '/appointments/create'
    | '/appointments/update'
    | '/horses/create'
    | '/appointments'
    | '/employees'
    | '/horses'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/about'
    | '/_authenticated/'
    | '/_authenticated/appointments/create'
    | '/_authenticated/appointments/update'
    | '/_authenticated/horses/create'
    | '/_authenticated/appointments/'
    | '/_authenticated/employees/'
    | '/_authenticated/horses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/horses/': {
      id: '/_authenticated/horses/'
      path: '/horses'
      fullPath: '/horses/'
      preLoaderRoute: typeof AuthenticatedHorsesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees/': {
      id: '/_authenticated/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AuthenticatedEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments/': {
      id: '/_authenticated/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AuthenticatedAppointmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/horses/create': {
      id: '/_authenticated/horses/create'
      path: '/horses/create'
      fullPath: '/horses/create'
      preLoaderRoute: typeof AuthenticatedHorsesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments/update': {
      id: '/_authenticated/appointments/update'
      path: '/appointments/update'
      fullPath: '/appointments/update'
      preLoaderRoute: typeof AuthenticatedAppointmentsUpdateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appointments/create': {
      id: '/_authenticated/appointments/create'
      path: '/appointments/create'
      fullPath: '/appointments/create'
      preLoaderRoute: typeof AuthenticatedAppointmentsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAppointmentsCreateRoute: typeof AuthenticatedAppointmentsCreateRoute
  AuthenticatedAppointmentsUpdateRoute: typeof AuthenticatedAppointmentsUpdateRoute
  AuthenticatedHorsesCreateRoute: typeof AuthenticatedHorsesCreateRoute
  AuthenticatedAppointmentsIndexRoute: typeof AuthenticatedAppointmentsIndexRoute
  AuthenticatedEmployeesIndexRoute: typeof AuthenticatedEmployeesIndexRoute
  AuthenticatedHorsesIndexRoute: typeof AuthenticatedHorsesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAppointmentsCreateRoute: AuthenticatedAppointmentsCreateRoute,
  AuthenticatedAppointmentsUpdateRoute: AuthenticatedAppointmentsUpdateRoute,
  AuthenticatedHorsesCreateRoute: AuthenticatedHorsesCreateRoute,
  AuthenticatedAppointmentsIndexRoute: AuthenticatedAppointmentsIndexRoute,
  AuthenticatedEmployeesIndexRoute: AuthenticatedEmployeesIndexRoute,
  AuthenticatedHorsesIndexRoute: AuthenticatedHorsesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
